### ISSUE TITLE
lora_gateway using with SX1308

### ISSUE THREAD

**Issue by Almaz1c** [Lora-net/lora_gateway#103]
Hello!
I am able to use lora_gateway on Raspberry Pi with SX1301 based board.
Does it possible to use this library with SX1308 based board in similar way? 
I mean can I drive SX1308 connected to Raspberry Pi using SPI?
Should I make some fixes of library for that?
I checked `loragw_reg.h` in `lora_gateway` and in `picoGW_mcu` - they looks similar.

**Comment by mcoracin** [comment]
Yes you can, it is compatible.
