### ISSUE TITLE
add support for SX1258

### ISSUE THREAD

**Issue by nestorayuso** [Lora-net/lora_gateway#104]
add support for new I/Q transceiver SX1258 for the 779 to 787 MHz Chinese
license-exempt frequency bands
[https://www.semtech.com/uploads/documents/DS_SX1258_V1.0.pdf](https://www.semtech.com/uploads/documents/DS_SX1258_V1.0.pdf)

**Comment by mcoracin** [comment]
no plan for this, for now at least.
