### ISSUE TITLE
Is it necessary that call sort function in almost evert function in jitqueue.c ?

### ISSUE THREAD

**Issue by nullptr0807** [Lora-net/lora_gateway#111]
I found that in file `jitqueue.c`

function `jit_enqueue` will sort the queue every time insert a packet.
function `jit_dequeue` will sort the queue every time dequeue a packet.
function `jit_peek` will sort the queue in the process of searching the needed packet when packet is too much in advance, in other words, in the worst case, it will sort `queue->num_pkt` times.

My question is that, is all those sorts necessary? Maybe use a heap to maintain this queue is a better way?

**Comment by mcoracin** [comment]
Maybe it can be optimized, if necessary.
If you have proposal, please put in in the packet_forwarder project, not in this one.
