### ISSUE TITLE
sx1276 Concentrator

### ISSUE THREAD

**Issue by surender128** [Lora-net/lora_gateway#112]
hi, 
    can i use sx1276 Concentrator in this project?

**Comment by Dollar-Yao** [comment]
> hi,
> can i use sx1276 Concentrator in this project?

You can't, the ADR function that SX1276 didn't support

**Comment by idevwebs** [comment]
> 
> 
> > hi,
> > can i use sx1276 Concentrator in this project?
> 
> You can't, the ADR function that SX1276 didn't support

Can you provide additional details?

https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT

> __Concentrator__: radio RX/TX board, based on Semtech multichannel modems 
> (SX130x), transceivers (SX135x) and/or low-power stand-alone modems (SX127x). 

I managed to get the sx1276 forwarding packets, but not with this library. There seems to be lots of code that is SX family specific.

**Comment by mcoracin** [comment]
This code is for sx1301 with sx1255/57.
