### ISSUE TITLE
LoRaWAN frequency point

### ISSUE THREAD

**Issue by Edward1688** [Lora-net/lora_gateway#118]
Hello,
I am setting up a  LoraWAN frequency point in the 868MHz range module, and the module with the point as below and 125KHz Bandwidth.
1: 868.1
2: 868.3
3: 868.5
What is the frequency of the channel of the loraWAN gatewat IC880A?

Thanks in advance!

**Comment by mcoracin** [comment]
I guess that you can configure your gateway channels as you wish.
