### ISSUE TITLE
Can't send using util_tx_test Plain LoRa to RF95

### ISSUE THREAD

**Issue by tibbis** [Lora-net/lora_gateway#119]
Hi!
I don't know why I am not able to send anything from my RAK831 Gateway to my RF95 node using util_tx_test.c program as plain LoRa packets. Things I checked:
- tested inverted modulation from gateway
- changed SyncWord on end node and set loraWAN_public=false
- frequency, CR, SF, BW, preamble

I can send from the RF95 node to the gateway using util_pkt_logger without any problems. I also tried with another Dragino-gateway that could send to the end node, so the end node is fine. 

What could be wrong? 

Thanks in advance!

**Comment by SaltyKarma** [comment]
Hey GitTibbe !
I have the exact same issue with the RAK831 LoRa Gateway. 
The node to node Tests have been successful(RF95<->RF95). 
 The test_loragw_tx runs fine, but i just could not receive packets from the RAK831 gateway :(

I have tried all the config jazz that you have mentioned. 

This is my Output for the following Linux command line:

 sudo ./test_loragw_tx -f 433.0:433.0 -b 125 -p 23 -r 8 -z 20 -t 10 -x 3 -i

Sending 3 packets on 433000000 Hz (BW 125 kHz, SF 10, 20 bytes
payload, 8 symbols preamble) at 23 dBm, with 10 ms between each
Sending 3 packets on 433000000 Hz (BW 125 kHz, SF 10, 20 bytes
payload, 8 symbols preamble) at 23 dBm, with 10 ms between each
INFO: concentrator started, packet can be sent
Sending packet number 1 ...OK
OK
Sending packet number 2 ...OK
OK
Sending packet number 3 ...OK
OK
Exiting LoRa concentrator TX test program
root@B827EBFFFEFF8E0C:/home/pi/RAK831_LoRaGateway/lora_gateway/libloragw#

But i am unable to receive that using a RF95 module. Not even noise :(


Please Help /\

**Comment by mcoracin** [comment]
If you both have issue with the same hardware, you should contact the hardware provider.

**Comment by sjain315** [comment]
@GitTibbe @SaltyKarma were you guys able to find out solution for this problem?
I'm facing the exact same issue
