### ISSUE TITLE
Using SX1301 (RAK833) with Windows 10

### ISSUE THREAD

**Issue by isorl** [Lora-net/lora_gateway#120]
Dear colleagues.
I am trying to operate SX1301 module (RAK833) on the Windows 10.
After setting up the device into Mini PCIe port the operation system recognized it as two COM ports.
So the question is: If it is possible to adopt this library for using with Windows 10 platform?
I would also be thankful for any other recommendations what drivers can i use for my purpose.

**Comment by mcoracin** [comment]
This software does not support this board "as is", it only targets a SPI interface.
You should get in touch with the module provider.
