### ISSUE TITLE
how to get decoded of payload 

### ISSUE THREAD

**Issue by Rajkumar181** [Lora-net/lora_gateway#121]
Any API is there for . To decode the payload.

Thanks
Raj

**Comment by nestorayuso** [comment]
You can not decode the payload at the gateway level because the payload is encrypted.
Only the network server knows the encryption key and can decode the payload.

some lorawan parser: https://github.com/JiapengLi/lorawan-parser

**Comment by Rajkumar181** [comment]
thanks for your reply. i have  encryption key, than i can do in gateway side.

**Comment by mcoracin** [comment]
You can refer to LoRaMac-node project to get the code for decryption.
This project does not provide any function for that.
