### ISSUE TITLE
SX1301 How to set register Low Data Rate Optimization

### ISSUE THREAD

**Issue by fanjm95** [Lora-net/lora_gateway#122]
Hi,
    I am testing the sensitivity of the gateway. SF12 sent by the machine always shows CRC validation error.I think the gateway should also be turned on for low datarate optimization.How to turned on  low datarate optimization?

**Comment by fanjm95** [comment]
.How to turned off low datarate optimization?

**Comment by fanjm95** [comment]
![image](https://user-images.githubusercontent.com/17777672/45217243-f69c0b80-b2d5-11e8-96f6-b1cec085cbe5.png)

**Comment by fanjm95** [comment]
I want to disenable low data rate optimization.but I do not know where to disenable?

**Comment by Dollar-Yao** [comment]
> I want to disenable low data rate optimization.but I do not know where to disenable?

Hi, you can search 'SET_PPM_ON' and find the definition,  the value of 'lora_rx_ppm_offset' is control the low data rate optimization.

**Comment by mcoracin** [comment]
It is enabled by default in the HAL for SF11/SF12:
https://github.com/Lora-net/lora_gateway/blob/a955619271b5d0a46d32e08150acfbc1eed183b7/libloragw/src/loragw_hal.c#L929
