### ISSUE TITLE
Getting DevAddr from received packets

### ISSUE THREAD

**Issue by victorcionca** [Lora-net/lora_gateway#123]
Hi,

I would like to access the DevAddr (MAC address) of the received packets. The util_pkt_logger tool has a "TODO: need to parse payload" next to the device MAC address.
However, the sx1301 datasheet doesn't mention anything about DevAddr, and this is not in the FIFO metadata.

Any insights would be appreciated.

Thanks,
Victor

**Comment by mcoracin** [comment]
Hi,
The sx1301 has no knownledge of the devaddr, it is just part of the packet payload.
So you can parse the received data payload, according to the LoRaWAN spec.
You can find an example in the packet forwarder here:
https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/src/lora_pkt_fwd.c#L1546

**Comment by victorcionca** [comment]
Hi,
That makes a lot of sense.
Thanks for the quick answer.
Victor
