### ISSUE TITLE
not getting proper range by using loranet lora-gateway and lora packet forwarder 

### ISSUE THREAD

**Issue by thaker123** [Lora-net/lora_gateway#124]
hi ,first of all  thank you for providing this code to successfully make the lora-gateway. when im using this my gateway working properly but only problem is not getting the range of lora-gateway. According to the explanation of hal library i properly configured all the things but after that this is not give the range as per my requirement,the max rang is only 500 to 600 m max. and the rssi=-119 max.
im using rak831 gate-way and rak811 lora-node, and used the loraserver of loraserver.io. all working properly only the problem is range, and i also set the rf tx power to 20 in test_lora_hal.c file. please give me right direction and suggestion how to increase the range of lora-gatway. please give me the response fast as much as possible. 
im waiting for your response
again thank you very much

**Comment by mcoracin** [comment]
There is no particular configuration to be done to extend the range, so if you have this kind of issue, it is rather related to your hardware or setup, than a software configuration.
