### ISSUE TITLE
I'm not able to Receive data/ack from RAK831 gateway to lora node 

### ISSUE THREAD

**Issue by sjain315** [Lora-net/lora_gateway#129]
Hi,

I'm new to the forums so apologies if this has been answered before but I've done a search and can't find anything on this topic...

I'm not able to Receive data/ack from RAK831 gateway to lora node 
note: I'm able to receive data from lora node to Gateway

my configuration is

    A RAK831 433MHz version
	I follow the instruction of https://www.thethingsnetwork.org/labs/story/rak831-lora-gateway-from-package-to-online to make rpi3 based lora gateway
    I just modify the global_config.json file according to Rak support recommandation and with my 433 frequency plan:
    I add it to TTN with India 865-867MHz freq plan (as 433 is not available)
	
    http://support.rakwireless.com/uploads/files/1516933601249-global_config_eu433.json
	I’m using a custom board with RFM98W 433mhz LoRa and Arduino Mini Pro.

For this testing I use basic tests programs comes with lora gateway library
util_pkt_logger program for  record all the packets received in a log file and 
util_tx_test program to send test packets with a LoRa concentrator

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
