### ISSUE TITLE
util_spi_stress.c -t 4

### ISSUE THREAD

**Issue by pandaxiao22** [Lora-net/lora_gateway#131]
Hi,
I use NUCLEO-L476RG(STM32L476)  to migration SX1301 's Hal Drivers.
When I use test_loragw_hal.c to test hal , the debug message is : 

ERROR: Failed to load fw 1
ERROR: Version of calibration firmware not expected, actual:19 expected:2
*** Impossible to start concentrator ***

I realized that there was a problem with SPI burst reading ， so i use util_spi_stress.c to test .
-t 1 、-t 2、and -t 3  are correct , but -t 4 have  problem .

It 's seem that “lgw_reg_w(LGW_RX_DATA_BUF_ADDR, test_addr);” not correctly modify the RX_DATA_BUF_ADDR .

**Comment by pandaxiao22** [comment]
It has been solved by improving SCK 's frequency from 0.625MHz to 5MHz.
But I meet a new problem , when i use test_loragw_hal.c to test hal , the debug message is :

lgw_setup_sx125x:407: Note: SX125x #0 version register returned 0x00
lgw_setup_sx125x:415: Note: SX125x #0 clock output disabled
lgw_setup_sx125x:469: Note: SX125x #0 PLL start (attempt 1)
lgw_setup_sx125x:469: Note: SX125x #0 PLL start (attempt 2)
lgw_setup_sx125x:469: Note: SX125x #0 PLL start (attempt 3)
lgw_setup_sx125x:469: Note: SX125x #0 PLL start (attempt 4)
lgw_setup_sx125x:469: Note: SX125x #0 PLL start (attempt 5)
ERROR: FAIL TO LOCK PLL
ERROR: Failed to setup sx125x radio for RF chain 0

Actually,it's always fail to lock pll when SCK 's frequency higer than 0.625MHz .

**Comment by nestorayuso** [comment]
If you are migrating lora_gateway from a linux host to a STM32 MCU why don't you use https://github.com/Lora-net/picoGW_mcu + https://github.com/Lora-net/picoGW_hal instead? your migration project is almost already done.

**Comment by pandaxiao22** [comment]
> If you are migrating lora_gateway from a linux host to a STM32 MCU why don't you use https://github.com/Lora-net/picoGW_mcu + https://github.com/Lora-net/picoGW_hal instead? your migration project is almost already done.

Thank you very much, do you know the different between sx1301 and sx1308 ?

**Comment by nestorayuso** [comment]
no difference, just working temperature range
