### ISSUE TITLE
ERROR: Version of calibration firmware not expected, actual:4 expected:2

### ISSUE THREAD

**Issue by pandaxiao22** [Lora-net/lora_gateway#134]
When I first power on the board , there is a error message : "ERROR: Version of calibration firmware not expected, actual:4 expected:2"
But when i reset the board by hand, the error disappear ,and the sx1301 can work normally . 
I reset it again , the error reappear ,it 's the same message : "ERROR: Version of calibration firmware not expected, actual:4 expected:2".
And i reset it again , the error disappear too ，it 's very regular .

Can somebody help me ,thanks .

**Comment by kevin-malter** [comment]
I got the same problem,someone said this is becase of SPI communication,but I don't know how to resole,how did you resoled it?

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
