### ISSUE TITLE
FSK Settings

### ISSUE THREAD

**Issue by EoinBullock** [Lora-net/lora_gateway#136]
Hi all,

I am trying to get an SX1276 board to talk to the IC880A board.
In my SX1276 I have the following tx settings:

`	    Write_Reg( REG_SYNCCONFIG,RF_SYNCCONFIG_SYNC_ON | RF_SYNCCONFIG_SYNCSIZE_2);

	    Write_Reg(REG_SYNCVALUE1,0xC1);

	    Write_Reg(REG_SYNCVALUE2,0x94);

	    Write_Reg( REG_PACKETCONFIG1,  RF_PACKETCONFIG1_PACKETFORMAT_VARIABLE | RF_PACKETCONFIG1_DCFREE_WHITENING | RF_PACKETCONFIG1_CRC_ON);

	    Write_Reg( REG_PACKETCONFIG2,  RF_PACKETCONFIG2_DATAMODE_PACKET); 

	    Write_Reg( REG_OPMODE,RF_OPMODE_MODULATIONTYPE_FSK | RF_OPMODE_SLEEP);`

25kbps, 30kHz freq deviation

I am confused about to get the ic880a to receive this.

Can anybody explain the difference between the registers LGW_FSK_PSIZE and LGW_FSK_TX_PSIZE?

I would also like to know what LGW_FSK_TX_PATTERN_EN is for? Is it for the SYNCWORD?

LGW_FSK_DCFREE_ENC I also need to know how to select whitening only from this register.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
