### ISSUE TITLE
SX1301 Calibration Test

### ISSUE THREAD

**Issue by sgodey** [Lora-net/lora_gateway#142]
Hello:

I am seeing a calibration test failure when I am running it on my RAK2245 concentrator on a RaspberryPi 3B. Below is the log output. Can the experts review this and let me know what is it I am doing wrong?

thanks in advance,
Sreekanth

**pi@raspberrypi:~/deps/lgw/platform-rpi/libloragw $ ./test_loragw_cal -a 925.1 -b 923.3 -t 902.3 -r 1257 -n 2
Library version information: Version: 5.0.1;
Radio type: 2
Radio A frequency: 925.100000 MHz
Radio B frequency: 923.300000 MHz
Number of calibration iterations: 2
Calibration command: brd: 0, chip: 1257, dac: 3

lgw_connect:532: INFO: no FPGA detected or version not supported (v0)
Note: success connecting the concentrator
lgw_setup_sx125x:407: Note: SX125x #0 version register returned 0x21
lgw_setup_sx125x:415: Note: SX125x #0 clock output disabled
lgw_setup_sx125x:469: Note: SX125x #0 PLL start (attempt 1)
lgw_setup_sx125x:407: Note: SX125x #1 version register returned 0x21
lgw_setup_sx125x:412: Note: SX125x #1 clock output enabled
lgw_setup_sx125x:473: Note: SX125x #1 kept in standby mode
WARNING: problem in calibration of radio A for image rejection
Rx A IQ mismatch: Amp: -12 Phi:  16 Rej: 47 dB Status: 135 | Debug: Rej: 50 dB Lna: 1 BB: 15 Dec:  7
Rx A IQ mismatch: Amp:  -7 Phi:  13 Rej: 50 dB Status: 143 | Debug: Rej: 52 dB Lna: 1 BB: 15 Dec:  7

Rx B IQ mismatch: Amp:   7 Phi:   7 Rej: 55 dB Status: 151 | Debug: Rej: 60 dB Lna: 1 BB: 15 Dec:  7
Rx B IQ mismatch: Amp:   8 Phi:   8 Rej: 55 dB Status: 151 | Debug: Rej: 58 dB Lna: 1 BB: 15 Dec:  7

Tx A calibration bypassed

Tx B calibration bypassed

Rx A IQ mismatch calibration statistics on   2 iterations (min, max):
Amp: -12  -7 Phi:  13  16 Rej: 47 50 dB (capt.: 50 52 dB)

Rx B IQ mismatch calibration statistics on   2 iterations (min, max):
Amp:   7   8 Phi:   7   8 Rej: 55 55 dB (capt.: 58 60 dB)
Note: success disconnecting the concentrator

End of radio calibration test
pi@raspberrypi:~/deps/lgw/platform-rpi/libloragw $**

**Comment by sgodey** [comment]
Below is calibration log which report problem with radio A for image rejection and radio B for TX imbalance.

Can experts comment on this? Is my concentrator bad?

pi@raspberrypi:~/deps/lgw/platform-rpi/libloragw $ ./test_loragw_cal -a 925.1 -b 923.3 -t 3 -r 1257 -n 10
Library version information: Version: 5.0.1;
Radio type: 2
Radio A frequency: 925.100000 MHz
Radio B frequency: 923.300000 MHz
Number of calibration iterations: 10
Calibration command: brd: 0, chip: 1257, dac: 3

lgw_connect:532: INFO: no FPGA detected or version not supported (v0)
Note: success connecting the concentrator
lgw_setup_sx125x:407: Note: SX125x #0 version register returned 0x21
lgw_setup_sx125x:415: Note: SX125x #0 clock output disabled
lgw_setup_sx125x:469: Note: SX125x #0 PLL start (attempt 1)
lgw_setup_sx125x:407: Note: SX125x #1 version register returned 0x21
lgw_setup_sx125x:412: Note: SX125x #1 clock output enabled
lgw_setup_sx125x:473: Note: SX125x #1 kept in standby mode
Rx A IQ mismatch: Amp: -6 Phi: 18 Rej: 50 dB Status: 143 | Debug: Rej: 46 dB Lna: 1 BB: 15 Dec: 7
**WARNING: problem in calibration of radio A for image rejection**
Rx A IQ mismatch: Amp: -10 Phi: 15 Rej: 48 dB Status: 135 | Debug: Rej: 45 dB Lna: 1 BB: 15 Dec: 7
WARNING: problem in calibration of radio A for image rejection
Rx A IQ mismatch: Amp: -11 Phi: 13 Rej: 48 dB Status: 135 | Debug: Rej: 46 dB Lna: 1 BB: 15 Dec: 7
Rx A IQ mismatch: Amp: -9 Phi: 15 Rej: 51 dB Status: 143 | Debug: Rej: 44 dB Lna: 1 BB: 15 Dec: 7
WARNING: problem in calibration of radio A for image rejection
.
.
.
Tx B DC offset I : 90 26 -86 123 -49 84 -46 -24
Tx B DC offset Q : 82 -84 37 -106 -20 -14 125 39
Tx B DC rejection: 28 26 25 22 25 20 25 27
Tx B DC debug BB : 15 15 15 15 15 15 15 15
Tx B DC debug Dec: 7 7 7 7 7 7 7 7
Tx B DC Status : 199
**WARNING: problem in calibration of radio B for TX imbalance**

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
