### ISSUE TITLE
Device can't join in OTAA when the program util_pkt_logger is running

### ISSUE THREAD

**Issue by Sertixzk21** [Lora-net/lora_gateway#143]
Once the program is off, my device automatically join, as if the program was occupying all my gateway traffic, even tho I can capture datas payloads without problem.

**Comment by mcoracin** [comment]
you cannot join with util_pkt_logger, it is just a tool to log incoming packet, not related to LoRaWAN.
And you cannot run util_pkt_logger in parallel of the lora_pkt_fwd utility as both would use the same HW, which is not supported.

**Comment by Sertixzk21** [comment]
I see, do you think there's a way to capture and send payload at the same time?
