### ISSUE TITLE
Gateway frequency selectivity

### ISSUE THREAD

**Issue by eoinoconnell87** [Lora-net/lora_gateway#145]
Hi all,

I have observed some very odd behaviour. I have this code running @909 MHz on my gateway from IMST and it is receiving packets from a nearby 868MHz Lora transceiver.

Why is the frequency selectivity so bad?

Eoin

**Comment by sp193** [comment]
If you made your EU868 tranceiver transmit (or a EU868 gateway receive) at 909MHz, it may not work well due to its filtering logic etc. 909MHz is likely out of range for EU868 hardware.
