### ISSUE TITLE
util_tx_continuius TX power level control

### ISSUE THREAD

**Issue by hamersin** [Lora-net/lora_gateway#149]
What is the best way to lower the TX output of the util_tx_continuous command? I am trying to lower it by about 2db. 

The command I am currently using is:
util_tx_continuous -f 923.3 --mod LORA --sf 7 --bw 500

I see that there are a couple of flags, but I am unsure as to what they actually do, and what their default values are.

--dig   <uint>   Digital gain trim
--mix   <uint>   Radio Tx mixer gain trim
--pa    <uint>   PA gain trim

**Comment by nestorayuso** [comment]
You need a calibration table for your board, If you are using the semtech 868MHz reference board you can use this:

https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/global_conf.json#L133-L139

For example, if you want a RF power of +10dBm, you need to set:
--dig Digital gain trim to 0
--mix Radio Tx mixer gain trim to 12
--pa PA gain trim to 1

more tables for different PCBs here: 
https://github.com/Lora-net/packet_forwarder/tree/master/lora_pkt_fwd/cfg

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
