### ISSUE TITLE
SX1301 register description

### ISSUE THREAD

**Issue by x893** [Lora-net/lora_gateway#15]
Hello,
can anybody help with SX1301 register description ?

Thanks in advance

**Comment by mcoracin** [comment]
Hello,

What do you need to know?
Semtech does not provide the full description of the registers, and the present code is there to show how to use it.

But if you have specific questions, I can try to answer.

Regards

**Comment by x893** [comment]
Hello,
i've simple question - how to use interrupt mode for SX1301 ?

**Comment by mcoracin** [comment]
Hello,
There is no interrupt mode on SX1301, you have to poll registers.

**Comment by x893** [comment]
Hi,
it very strange - DIO lines exists.
Semtech looks as most china company w/o any documentation.

**Comment by mcoracin** [comment]
Hello,
No interrupt mode on SX1301.
Concerning the documentation, SX1301 is an exception in the sense that it is purposely not documented.
The present source code is given as a reference of usage and configuration.

If you have specific questions about the driver code, you can ask, we'll try to answer.

Regards

**Comment by x893** [comment]
I port gateway from linux to FreeRTOS with low power MCU (STM32L and may be to EFM32) but to reduce consumption think about interrupt mode. Also i use GSM modem to provide link to internet or microSD for standalone application. Thanks for your answer about interrupt.

**Comment by fanjm95** [comment]
SX1301 How to set register  Low Data Rate Optimization?

**Comment by 1082008** [comment]
https://github.com/Lora-net/lora_gateway/wiki/SX1301-GPIO-output-configuration

@x893 If you wire `RX_BUFFER_NOT_EMPTY` GPIO of SX1301 to one of your MCU's GPIOs, you can spare your SPI busy loop polling and just read received LoRa data packets on a rising edge. It works, I've just tried. This also means a better response time because we are possibly not in sleep when a packet arrives but can react instantly.

**Comment by ttangzr** [comment]
Hi,
I try to get the GPIO output of SX1308 pico gateway with STM32F4 MCU. I set the `LGW_GPIO_SELECT_OUTPUT` as follows:

``` C++
lgw_reg_w(LGW_GPIO_MODE, 31);
lgw_reg_w(LGW_GPIO_SELECT_OUTPUT, 4);
```

GPIOs table will be then as follow (refer to Table 7 of SX1301 DS)
- GPIO[0] -> sensor_0_detect
- GPIO[1] -> sensor_0_sync
- GPIO[2] -> sensor_0_header_val
- GPIO[3] -> 1’b0
- GPIO[4] -> 1’b0

But I have some questions:
1. Does anybody know the TYPE of these output values? Analog or digital high/low level signals?
2. What does the 1’b0 mean?

Thanks.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
