### ISSUE TITLE
Led flashses on ic980a but no packet received

### ISSUE THREAD

**Issue by eoinoconnell87** [Lora-net/lora_gateway#151]
Hi there,
I have a weird issue currently where around 1 in every 10 packets that the ic980a will flash the led for a packet received but nothing is returned by lgw_receive.

I am sending packets from a transmitter and I also see activity on the spectrum analyser. Do you know what could cause this? My transmitter is only a couple of metres away but TX power is on -10dBm

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
