### ISSUE TITLE
Receive uplinks & downlinks

### ISSUE THREAD

**Issue by MrKoppot** [Lora-net/lora_gateway#157]
Hi All,

Is it possible to receive uplink and downlink packets simultaneously with the SX1301? 

I have read "Receive unfiltered LoRa Frames", issue #29 in the lora_gateway git, and "LoRaWAN Gateway as a Repeater" issue 80 in the packet_forwarder git, as well as the SX1301 datasheet.

From reading these, I know it is possible to receive either/or by setting the IQ inversion settings appropriately. 
**My question is: there are two radios used for Rx inside the SX1301, can one be set to listen for uplinks and the other for downlinks?** I get the feeling the preamble detection that filters unwanted uplink (or downlink) packets is done with both Rx streams together- with no ability to separate them.

I have tried reading through loragw_reg.h/.c, but there is little to no explanation for what the registers do. Is there a resource that explains the registers anywhere?

Thank you for any help in advance.

**Comment by Doom4535** [comment]
@MrKoppot I believe the two radios are used to expand the input frequency range as each of the referenced radios ([SX1257](https://www.mouser.com/datasheet/2/761/DS_SX1257_V1.2-1360316.pdf)) has a bandwidth of 500 KHz and the SX130x needs 1 MHz to scan all eight 125 KHz channels.  If you were to configure each with different polarities you would only receive 1/2 the band at best.

With that said, have you made any progress on this and/or found anyone with information on the registers?  Semtech doesn't seem to have published hardly anything about these chips, and just says 'go to the HAL' (where the registers have no description other than their names).
