### ISSUE TITLE
Is hybrid mode included in this version?

### ISSUE THREAD

**Issue by sheenhx** [Lora-net/lora_gateway#16]
Hi, recently your FAE Michael Fink told us that the hybrid mode is in this github. But we can't find it anywhere. Do you have plan to release it soon? Thanks!

**Comment by mcoracin** [comment]
Hi,
You should be able to use the github version, using the global_conf.json.US902 config file provided in the packet forwarder /cfg directory.
Even though I could not test it myself as I don't have such gateway.

Let me know if you can test it.

Regards

**Comment by sheenhx** [comment]
We have successfully build the FPGA version and tested it. And we are the only company which can do the mass production
If you want we can send you one for free:)

**Comment by mcoracin** [comment]
Great news, congratulations!
We would be glad to receive one for sure! :)

**Comment by sheenhx** [comment]
Please send me your address to xin@airfy.com   :+1:
