### ISSUE TITLE
serial for gps should be disabled the echo function

### ISSUE THREAD

**Issue by rossihwang** [Lora-net/lora_gateway#17]
Hi
As I am working on the beacon function for class B, I connect the my Raspberry Pi B+ and ic880A with the GPS moudule (neo-6m-0-001).

Then I found many useless information like

```
$GPTXT,01,01,01,NMEA unknown msg*58
...
```

After connecting the uart_tx pin of rpi to my pc, I found it echo what it receive to the pc. That is the reason the GPS kept sending the warning message. Thus I add some code to the loragw_gps.c to disable the echo function.

```
int lgw_gps_enable() {
    ...
    ttyopt.c_lflag &= ~ECHO; // before tcsetattr()
    ...
}
```

Anyone has the same issues??

**Comment by mcoracin** [comment]
Hello,

Thank you for reporting this issue, we'll integrate this change in next release.
