### ISSUE TITLE
Why set gpio direction twice in iot_sk_init()@reset_lgw.sh?

### ISSUE THREAD

**Issue by andrewintw** [Lora-net/lora_gateway#170]
Can someone explain after set IOT_SK_SX1301_RESET_PIN as gpio output in line 30 and do reset, why it need to set as gpio input in line 37? Does it really necessary?

https://github.com/Lora-net/lora_gateway/blob/master/reset_lgw.sh

**Comment by ryangriggs** [comment]
I have a related question: what is the point of the 'stop' command in the reset script at all?  When would this ever be used? It simply unexports the reset GPIO pin, which is done anyway at the end of the "start" command.
This is confusing and maybe unnecessary?
