### ISSUE TITLE
3.2.1 version spi native issue on Linux kernel 2.6.30

### ISSUE THREAD

**Issue by queifaro** [Lora-net/lora_gateway#18]
Hi All,
in a lgw_spi_w function (spi_native) are present the following settings:
k.speed_hz = SPI_SPEED and k.bits_per_word = 8 

that kind of protocol is not supported in atmel_spi driver present in 2.6.30 linux kernel.

Speed and bits per word seams to be already programmed into lgw_spi_open function so is there any specific reason to set it also in lgw_spi_w function ?

thanks in advance
Regards
Fabio

**Comment by mcoracin** [comment]
Hello Fabio,

It is true that setting this in lgw_spi_w function is redundant as it has already been set in lgw_spi_open.
If it is not supported by your kernel, you can safely remove those calls.

Best regards
