### ISSUE TITLE
Inconsistent 'TX imbalance' warning

### ISSUE THREAD

**Issue by tj12961** [Lora-net/lora_gateway#19]
The hardware in question is the iC880a-SPI concentrator controlled using the SPI interface of the Raspberry Pi 3 using the spi_bcm2835 module.

Upon calling lgw_start(), occasionally the debug information shows 'WARNING: problem in calibration of radio A for TX imbalance'. 

This message is seemingly generated based on the state of an SX1301 register for which documentation is unavailable. Is this warning serious or can it be ignored?

Before accessing the SPI interface, the hardware has been reset.

The configuration settings for the RF chain are displayed as follows:

```
rf_chain 0 configuration; en:1 freq:868500000 rssi_offset:-169.000000 radio_type:2 tx_enable:1
rf_chain 1 configuration; en:1 freq:868500000 rssi_offset:-169.000000 radio_type:2 tx_enable:0
```

Additionally, the TX gain table has been configured with values obtained from the iC880a documentation.

The same message occasionally appears when running the 'util_tx_test' program.

**Comment by mcoracin** [comment]
Hello,
First of all, we just noticed that the warning message is wrong, it should be
"problem in calibration of radio A for TX DC offset".

Is the warning serious, well it could be.

I suggest to contact IMST or Semtech's RF support to reproduce the issue and understand how to fix it.

If the problem occurs occasionally and you need a quick fix, I suggest to add a retry mechanism on the calibration fw loading in the lgw_start() function. I can help you on this if needed.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
