### ISSUE TITLE
SX1301 reference board with version 1.2.x of library

### ISSUE THREAD

**Issue by sylvain-miermont** [Lora-net/lora_gateway#2]
When using version 1.2.x of the library, the SX1301 is not fully supported:
 * sensitivity is bad (eg. -127dBm for SF12/125kHz, instead of -141dBm) due to gain settings being optimized only for the FPGA-based board
 * the multi-SF RX channels 4 to 7 are not usable
 * the RSSI value is not properly calibrated and has an offset of 11 dBm

Support for SX1301 boards is scheduled for version 1.3 and beyond.

**Comment by borud** [comment]
So is this issue closed?

**Comment by mcoracin** [comment]
Yes, issue closed.
