### ISSUE TITLE
LoRaWAN Gateway Settings

### ISSUE THREAD

**Issue by suspirik** [Lora-net/lora_gateway#20]
Hi,
 
I am working on microchip LoRa RN 2483 -raspberry pi c 2011 gateway and I have to set server ip and ports. But on the instructions of semtech network server gateway settings, there are files such as sys_config or global_config but I do not have them on raspberry so I download packet forwarder to get that files. But on the cooking-hacks site where I have instructions for raspberry site, they do not have such instructions and no mention about packet forwarder nor lora gateway application. Do you have any suggestion? Should I go on witht this code and packet forwarder or is it different?
I have arduPi lib and LoRaWAN lib so far.
 
*on the cooking hacks site they suggested to follow semtech's instructions but I need your confirmation if this app and packet forwarder suitable also my network devices.
Thanks in advance...

**Comment by mcoracin** [comment]
The lora_gateway and packet_forwarder code provided here is intended to be used with SX1301 based LoRa gateway.
