### ISSUE TITLE
LoRa Gateway without GPS Signal Available

### ISSUE THREAD

**Issue by shankuuuu** [Lora-net/lora_gateway#23]
Hi,

For our gateway deployment, we have to deploy the gateways inside buildings were there is no guarantee of GPS signal. But the gateway has a connection to NTP server.

In this scenario, do I have to make any changes to current source code available ?
Will the gateway still work without able to get a proper GPS signal?

Regards,
Shankar

**Comment by mcoracin** [comment]
Hi,

It is not mandatory to have a GPS signal to have a functionnal gateway.
Just use a global_conf.json without "gps_tty_path" set.
https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/cfg/global_conf.json.PCB_E286.EU868.basic

Regards
