### ISSUE TITLE
reference design doc?

### ISSUE THREAD

**Issue by laoqr** [Lora-net/lora_gateway#28]
Hello,
I am wondering if there are some reference design documents for lora-gateway with sx1301?

Thanks!

**Comment by iBrick** [comment]
No working, only this: https://github.com/will127534/LoRa-concentrator

**Comment by Jungok** [comment]
https://github.com/Lora-net/lora_gateway
This source is contiributed by semtech

**Comment by zhoubx123** [comment]
Jungok，can you tell me your design file with the fpga?Raspberry pi  board needs to connect what pins?
thank you !

**Comment by Jungok** [comment]
@zhoubx123 
Hello, Zhoubx123. I am having the IOT SX1301 starter kit with Raspberry pi 2 for Korea. The board name is PCB_E3401.5. It simply connect to Raspberry through SPI. I couldn't share my design file because it is confidential. However, You can get it from Semtech.  

In addition, I heard that FPGA is only for LBT, and some countries don't need to LBT.

**Comment by zhoubx123** [comment]
@Jungok

**Comment by zhoubx123** [comment]
@Jungok

**Comment by zhoubx123** [comment]
@Jungok

**Comment by zhoubx123** [comment]
@Jungok

**Comment by zhoubx123** [comment]
@Jungok
Can you tell me your email ?
I have some questions to ask you.
My email is 724784058@qq.com.

**Comment by zhoubx123** [comment]
@Jungok
Can you tell me your email ?
I have some questions to ask you.
My email is 724784058@qq.com.

**Comment by zhoubx123** [comment]
Jungok
Can you tell me your email ?
I have some questions to ask you.
My email is 724784058@qq.com.

**Comment by zhoubx123** [comment]
Jungok
Can you tell me your email ?
I have some questions to ask you.
My email is 724784058@qq.com.

**Comment by zhoubx123** [comment]
Jungok
Can you tell me your email ?
I have some questions to ask you.
My email is 724784058@qq.com.

**Comment by zhoubx123** [comment]
Jungok
Can you tell me your email ?
I have some questions to ask you.
My email is 724784058@qq.com.

**Comment by ucasws** [comment]
@Jungok  could you tell me how to sign NDA with semtech? please contact me,thank you ,my eamil is shuai.wang@mail.sim.ac.cn

**Comment by mcoracin** [comment]
Please contact Semtech support for this kind of requests.
