### ISSUE TITLE
Single-channel gateway

### ISSUE THREAD

**Issue by suhamera** [Lora-net/lora_gateway#37]
Hi,

I want to adapt library to work in Single-channel gateway mode. It is necessary to collect a cheap gateway based on SX127X modules for testing and debugging. Is it even possible to do this on the  library by deleting a number of functions in **loragw_hal** and **loragw_reg** or easier to write such a library from scratch?

Thanks!

**Comment by mcoracin** [comment]
Hi,

I think it will be as quick to develop it from scratch, as the lora_gateway lib is dedicated to SX1301. But I've never done the exercise, so it's your call. :)

Regards
