### ISSUE TITLE
FPGA hex format

### ISSUE THREAD

**Issue by linux4life798** [Lora-net/lora_gateway#38]
I am trying to flash the FPGA using the SEGGER JFlashSPI utility, but it seems to want a binary image.

I see that the FPGA images are now in a .hex format. What type of hex format is this? Intel, Motorola, Extended Tektronix hex?
Can I simply build a binary image composed of the bytes spelled out in the hex file?

Thanks,

Craig

**Comment by linux4life798** [comment]
I figured it out. Here is what I learned:

The Segger seems to be useless without proper SPI licensing and a more expensive programmer.
You can program the FPGA's flash using a Raspberry Pi, flashrom utility, and a custom hex to bin script that I will attach here.
Yes, the hex file seems to just be a list of the bytes that compose the FPGA flash image.

1) Use my attached shell script that takes Semtech's published FPGA ".hex" file and produces a proper sized ".bin" file for flashrom. The script simply concatenates the bytes with extra zero padding.
EX: `./sx1301hex2bin.sh ~/src/lora_gateway/fpga/SX1301_FPGA_NOTCH_PROG_SPECTRAL_SCAN_v31.hex ~/newimage.bin`
2) Connect the RPi SPI0 w/CE0 to the SX1301AP2 FPGA SPI program port and enable SPI using the raspi-config tool.
3) Install flashrom
EX: `sudo apt-get install flashrom`
4) Flash the FPGA using flashrom
`flashrom -p linux_spi:dev=/dev/spidev0.0 -w ~/newimage.bin -V -c "M25P10-A"`

You may want to backup the original image by doing the following:
`flashrom -p linux_spi:dev=/dev/spidev0.0 -r ~/original_image.bin -V -c "M25P10-A"`

Best,

Craig

[sx1301hex2bin.sh.zip](https://github.com/Lora-net/lora_gateway/files/715712/sx1301hex2bin.sh.zip)

**Comment by mcoracin** [comment]
Thank you Craig, it will be very useful for a lot of users I think!

**Comment by pierreduf** [comment]
Hi Craig,

Thank you for that piece of valuable information ! I'm trying to backup (and change) the FPGA firmware on a LoRa GW but that doesn't seem to work.

I've compile flashrom for the right architecture (and indeed it's starting and working without any error) but it doesn't seem to find any matching FPGA (even forcing the M25P10 like you did).

My SPI device is /dev/spidev1.0, and I've adapted the command accordingly.

Do you have any other tips or experience on other GW that I could try ? I guess that's related to the SPI muxing done by the SX1301 : I've got the feeling that flashrom sees only the SX1301 and not the FPGA behind it (but I may be wrong, I'm not really an expert of that kind of thing).

BR,

Pierre

**Comment by linux4life798** [comment]
Hi Pierre,

You need to make sure that you are connected to the actual flash SPI channel and not the 1301 / FPGA normal data SPI channel. Note that the M25P10 device is actually just a standard SPI flash chip that is then connected to the iCE40 FPGA to load the image at boot.

For future reference, I believe the FPGA serves as the SPI mux between the SX1301 and the extra SX1273/76, but of course this is only applicable to the normal data SPI lines.

**Comment by linux4life798** [comment]
If I recall correctly, you also need to hold the board in reset so that you can talk to the flash chip directly.

**Comment by pierreduf** [comment]
Thank you Craig for you quick answer ! I think that's clearer for me. I'm going to try a few things and let you know if I succeed.

**Comment by linux4life798** [comment]
Sounds good, best of luck!

**Comment by pierreduf** [comment]
Done it with a Raspberry Pi and another tool called spiflash and it worked ! Thank you for your help.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
