### ISSUE TITLE
AGC MCU firmware / GPIO documentation

### ISSUE THREAD

**Issue by BWhitten** [Lora-net/lora_gateway#40]
The default setting of the GPIO pins from the SX1301 is to allow the AGC MCU to have complete control.
https://github.com/Lora-net/lora_gateway/blob/ddc5e5079ad76c42935f6a5d382194022984f77d/libloragw/src/loragw_hal.c#L714

What is the function of the AGC [firmware](https://github.com/Lora-net/lora_gateway/blob/ddc5e5079ad76c42935f6a5d382194022984f77d/libloragw/src/agc_fw.var) and what are the signals that are produced on the GPIO by default by the AGC?
Are any of the signals packet RX & TX?

**Comment by mcoracin** [comment]
Please find information here:
https://github.com/Lora-net/lora_gateway/wiki/SX1301-GPIO-output-configuration
