### ISSUE TITLE
How do I find the current version of the firmware FPGA Kerlink (ERROR: Spectral Scan is not supported (0x0))

### ISSUE THREAD

**Issue by Ssergeyy** [Lora-net/lora_gateway#41]
Hey.
How do I find the current version of the firmware FPGA Kerlink Station without SPN?

I ran util_spectral_scan v4.1.0
+++ Start spectral scan of LoRa gateway channels +++
Note: SPI port opened and configured ok
Note: success connecting the concentrator
Note: SPI read success
ERROR: Spectral Scan is not supported (0x0)

Thank you in advance.

**Comment by mzemb** [comment]
I'm not sure if that's what you are looking for, but you have a lot of versions given by /usr/local/bin/get_version

**Comment by mcoracin** [comment]
Please contact Kerlink support.
