### ISSUE TITLE
Changing KHZ, bandwidth of a channel

### ISSUE THREAD

**Issue by Artysteel** [Lora-net/lora_gateway#44]
Good day,

Is it possible to change channel settings as following?

"chan_multiSF_0": {
    /* Lora MAC channel, 125kHz, all SF, 868.1 MHz */
    "enable": true,
     "radio": 1,
     "if": -400000,
     "bandwidth": 7800,
     "datarate": 585
}

I want channel to operate on 7.8kHz and width 585bps

**Comment by mcoracin** [comment]
Those bandwidth and datarate are not supported by LoRa demodulator.
