### ISSUE TITLE
Multi-receive on CN470 Band

### ISSUE THREAD

**Issue by ckt1010** [Lora-net/lora_gateway#45]
Hi all,
Did some one test this code on CN470 Band before?
There is a strong things from my test, your can see my log below.

> lgw_receive:1120: FIFO content: 3 60 0 7 19
> lgw_receive:1139: [0 17]
> Note: LoRa packet
> lgw_receive:1120: FIFO content: 2 89 0 5 19
> lgw_receive:1139: [6 17]
> Note: LoRa packet
> lgw_receive:1120: FIFO content: 1 b2 0 5 19
> lgw_receive:1139: [7 17]
> Note: LoRa packet
> 
> INFO: Received pkt from mote: 0603F073 (fcnt=0)
> 
> INFO: Received pkt from mote: 0603F073 (fcnt=0)
> 
> JSON up: {"rxpk":[{"tmst":20893108,"chan":6,"rfch":0,"freq":475.900000,"stat":1,"modu":"LORA","datr":"SF12BW125","codr":"4/5","lsnr":-12.0,"rssi":-64,"size":25,"data":"gHPwAwaAAAACQArgE/88ZErlDBWapnChrA=="},{"tmst":20893108,"chan":7,"rfch":0,"freq":476.100000,"stat":1,"modu":"LORA","datr":"SF12BW125","codr":"4/5","lsnr":10.2,"rssi":-13,"size":25,"data":"gHPwAwaAAAACQArgE/88ZErlDBWapnChrA=="}]}
> INFO: [up] PUSH_ACK received in 0 ms
> INFO: [down] PULL_RESP received  - token[0:0] :)

This fcnt 0 packet has been received twice(maybe three, first is CRC bad). But actually it only send one time, and at 476.1Mhz. Why it also receive at 475.9Mhz? Is there interference? Or maybe I make some mistake on   config file?

**Comment by mcoracin** [comment]
Hello,

It seems that you are sending a very strong signal (rssi=-13 on 476.1).
You may get an image of that signal on other channels.

Could you try the same with a lower power?

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
