### ISSUE TITLE
build failed when compile in util_tx_continuous utility

### ISSUE THREAD

**Issue by Kutoc** [Lora-net/lora_gateway#5]
the root cause is that it missed the obj directory in util_tx_continuous when GCC link the x.o object file.

**Comment by JiapengLi** [comment]
Missing empty obj directory is the trouble. 
It will be good if Makefile could be responsible to detect and create obj directory instead of keep an empty and no meaning obj directory.

**Comment by mcoracin** [comment]
this will be fixed with next release, thanks for reporting.
As suggested by JiapengLi, the Makefile will handle it.
