### ISSUE TITLE
util_pkt_logger: ERROR failed to load fw 1?

### ISSUE THREAD

**Issue by canhthang** [Lora-net/lora_gateway#50]
I'm using Raspberry Pi 3, RHF0M301 - 915 to make a gateway. I ran util_pkt_logger and got this:

ERROR: failed to load fw 1
ERROR: Version of calibration firmware not expected, actual:0 expected:2

Can anyone please check and help me? I am new to github.

**Comment by reissjason** [comment]
Check the supplied power. If the read/write is failing the read will return 0.

**Comment by ClementHuchet** [comment]
Hi, verify you wiring and make sure you connected the grounds of both devices.

**Comment by canhthang** [comment]
Thank you, I didn't know that I need to connect the grounds of both devices. It worked.

**Comment by ClementHuchet** [comment]
My pleasure , cheers ;)

**Comment by van-cuong-nguyen** [comment]
Dear @CanhThang,
Could you share with me your experience in building a gateway with RHF0M301 - 915  and Pi 3?
I got this error. Many thanks.
![image](https://user-images.githubusercontent.com/19818435/32980801-4839ec24-cca8-11e7-8d92-66171ed960b2.png)

**Comment by 3nd0y** [comment]
Hi i have the same issue, i checked the wiring is good, then ground both of them connected but still have error
ERROR: failed to load fw 1
ERROR: Version of calibration firmware not expected, actual:0 expected:2

is there other answer?

**Comment by arihantdaga** [comment]
Same here with me. My wirings are good. I bought this lite Gateway which comes pre assembled, i dont think wiring is having anything wrong, i am giving power of 5v 2A. Still getting this same error.. 
ERROR: failed to load fw 1
ERROR: Version of calibration firmware not expected, actual:0 expected:2

And using util_spi_stress -t 4
Returns read values 00
Can somebody please suggest what is going wrong here..

**Comment by arihantdaga** [comment]
I am facing the same issue.. 
Did anyone figure it out.. 
@3nd0y ANy luck.. ?

**Comment by arihantdaga** [comment]
@3nd0y
