### ISSUE TITLE
Problems with SX1301

### ISSUE THREAD

**Issue by canhthang** [Lora-net/lora_gateway#52]
I use Raspberry Pi 3 with RH0M301 (from RisingHF) to make a LoRa gateway with code from:
https://github.com/Lora-net/lora_gateway
And my end devices is made by RF95 and a microcontroller.

I try util_pkt_logger to receive packet from my end devices (without LoRaMAC), with config parameter from here: https://github.com/TheThingsNetwork/gateway-conf/blob/master/AS2-global_conf.json

I found out that sometimes my gateway receive a packet from unknown device, not from my end devices. I tested that my end devices can communicate with each other.

Can anyone tell me what is missing here? What are the requirements which both gateway and device have to follow to send or receive packet?
Thank you in advance!

**Comment by mcoracin** [comment]
Hello,

Have you progressed on this?

Do you have access to a reference gateway or a reference node that is proven to be working, in order to separate issues?

Which software are you using on the end-node side?

Maybe one first thing to check is that you are using the same syncword on both ends:
- On the GW side, the "lorawan_public" field set to true indicates that you are using a syncword of 0x34 (instead of 0x12).
- On the node side, by default, the register RegSyncWord is sent to 0x12, unless your sw sets it to 0x34.

**Comment by canhthang** [comment]
It's true. I should have checked the syncword first.
I have another question about FPGA. I use RH0M301 (from RisingHF) and I can not start FPGA. Can you check for me if this device supports FPGA?

**Comment by mcoracin** [comment]
I don't think there is a FPGA on this board, but better check with RisingHF. I nerver used this board.

**Comment by canhthang** [comment]
So how can I use LBT without FPGA? I work in AS923.
Thank you so much @mcoracin

**Comment by mcoracin** [comment]
You cannot do LBT without the FPGA and the extra SX1272 which is there for carrier sensing while the gateway is operating.

In this case, you have to disable the LBT feature in the hal/packet_forwarder.

**Comment by canhthang** [comment]
I now can receive packet from my node (RF95). I tried to send packet from RH0M301 back to node by util_tx_test. I saw the successful packet transmission but my node did not receive the packet. Can you tell me what is missing here?

**Comment by mcoracin** [comment]
Can you give the complete command line you are using with util_tx_test?
Which software do you use on the end-node side?

**Comment by canhthang** [comment]
Sorry I use util_tx_continuous. I mix it with util_pkt_logger to create a main file like this:
https://github.com/CanhThang/temp/blob/master/main.c
I use Keil C and a Cortex - M0 MCU.

**Comment by mcoracin** [comment]
why don't you use the packet forwarder to send and receive packets?
[https://github.com/Lora-net/packet_forwarder](https://github.com/Lora-net/packet_forwarder)

On the end-node side, which LoRaWAN software are you using?

I don't understand the point of mixing util_pkt_logger with util_tx_continuous...

**Comment by canhthang** [comment]
I want to make my own gateway code from lora_gateway code, and connect to my server by MQTT. I changed the gateway module recently from SX1276 (small project) to RH0M301 (for bigger project). Now I am trying to send from gateway to node, the other parts I have done before.

**Comment by mcoracin** [comment]
You could just replace the UDP part of the packet_forwarder with MQTT, right?
util_tx_continuous is more a RF validation tool, rather that something to send LoRa packets.

If you want to get support, I would suggest to validate that you gateway is correctly working using a proven software, with a working LoRaWAN end-node.
Then it is up to you to change everything with what you want. :)

**Comment by canhthang** [comment]
I tried your code: https://github.com/Lora-net/lora_gateway/blob/master/util_tx_test/src/util_tx_test.c (-r 1257 -f 920) to send packet in the same parameters with node.
Refer to this comment: https://github.com/Lora-net/lora_gateway/issues/27#issuecomment-256575794, can I use util_tx_test to send packet without server? I am using non protocol packet.
If yes, are there any requirements with antenna, or syncword, or anything that I forget to set the same in gateway and node?

**Comment by mcoracin** [comment]
The polarity has to be inverted, you need to add the -i option to util_tx_test.

**Comment by canhthang** [comment]
Dear Mr @mcoracin,
I now can control SX1301 and do the tasks I want. Thank you for supporting me devotedly and enthusiastically.

I still have some problems that need you to help:

1. About the stability (or duration - sorry I don't know the specific technical word) of network:
If I let end device connect and keep interacting, everything will be fine. If I disconnect (power off, reset,...) my end device and reconnect several times, my gateway (Pi + SX1301) sometimes cannot receive any packet, and I have to restart the gateway to make it work.

2. About the distance between gateway and devices:
I tried to test the distance, and my network only can work within few meters. Of course I know that I should upgrade the antenna, but can you tell me are there any parameters or method to improve in the code (such as TX power)?

Regard,
Thang

**Comment by canhthang** [comment]
Mr @mcoracin, can you help me?

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
