### ISSUE TITLE
Hi，FPGA for CN470.hex

### ISSUE THREAD

**Issue by zhoubx123** [Lora-net/lora_gateway#53]
Hi, Is there a SX1301_FPGA_200K_NOTCH_LBT_SPECTRAL_SCAN_863_v33.hex corresponding to the CN470 file?

**Comment by mcoracin** [comment]
Hi,
No there is no FPGA image available for CN470.
The FPGA design exists to handle 27dBm in EU868 band, and LBT in AS923. Neither are required for CN470.
