### ISSUE TITLE
End-node can receive packets but gateway can't receive end-node's packets

### ISSUE THREAD

**Issue by 18819456885** [Lora-net/lora_gateway#63]
Hello!
I have a problem.My End-nodes can receive packets but gateway can't receive end-node's packets.I use How can I do?I use  \lora_gateway\util_tx_testtest_loragw_hal.c,but receice nothing.I am sure my end-nodes sending packets now.
Thank you in advance!

**Comment by vikasrohal** [comment]
Cross check frequency of End node and configured frequency in  global_config.json

**Comment by 18819456885** [comment]
@vikasrohal
Thanks for your replay!!!
 However, I use test_loraway_hal.c to test.And it seems no need to change global_config.json.My nodes and gateway use the same frequency.It is 480M.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
