### ISSUE TITLE
1301  gateway can't receive end-node's packets?

### ISSUE THREAD

**Issue by 18819456885** [Lora-net/lora_gateway#64]
Hello everyone! 
I have a problem.
MY 1301 gateway uses sx1301 and two sx1255.My end-node uses stm32 MCU and sx1278 to send and receive packets.And i use  \lora_gateway\libloragw\test_loragw_hal to send and receice packets.
My order is ./test_loragw_hal -a 480 -b 480 -t 480 -r 1255 -k 1
Howerver,when my gateway is sending packets.My end-node can receive my gateway's packets.
When my end-node sends packets. My gateway can't receice packets.Can someone help me?
Thank you in advance!

**Comment by vikasrohal** [comment]
Cross check Tx Frequency(End Device) and Rx Frequency(Global_config.json)
Use pkt logger to receive packets

**Comment by mcoracin** [comment]
No answer on @vikasrohal comment, closing the issue
