### ISSUE TITLE
Packet drop issue with multiple devices 

### ISSUE THREAD

**Issue by vikasrohal** [Lora-net/lora_gateway#65]
Hi,
I am testing with 5 End devices and observe few packets are drop but End devices Send these packets 8 times and no single packet received by gateway 

As per attached log FCNT=7 of (0000009) device address droped but End Device Send this packet 8 times  with CRC ok (as per util_pkt_logger log).

Its happen with other devices also.

Lora Gateway version - v5.0.1
Lora packet forwarder - v4.0.1
Lora Mac Master - v4.3.2
Hardware:
raspberry pi and iC880a(IMST) 

[2_Aug_5_devices_2nd_test.txt](https://github.com/Lora-net/lora_gateway/files/1196059/2_Aug_5_devices_2nd_test.txt)

**Comment by xjh200858** [comment]
Yes,I have the same problem.
src/jitqueue.c:280:jit_enqueue(): ERROR: Packet (type=0) REJECTED, collision with packet already programmed at 1551992540 (1552155148)

**Comment by satideur** [comment]
I think it would be helpful if you attach the Tx log because the packets could be colliding

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
