### ISSUE TITLE
SX1301 compile issue 

### ISSUE THREAD

**Issue by allionWilliam** [Lora-net/lora_gateway#71]
hi everyone 

I have error message after I use "make" command to compile the lora_gateway file.
I am really not familiar with coding, could anyone help me ?
I got the source from  https://github.com/Lora-net/lora_gateway

pi@raspberrypi:~/¬/Lora/lora_gateway $ make
make: Warning: File 'Makefile' has modification time 2001791 s in the future
make all -e -C libloragw
make[1]: Entering directory '/home/pi/¬/Lora/lora_gateway/libloragw'
make[1]: Warning: File 'library.cfg' has modification time 2001791 s in the future
*** Checking libloragw library configuration ***
#File initialization
# Release version
Release version   : 5.0.1
# Debug options
# end of file
*** Configuration seems ok ***
mkdir -p obj
gcc -c -O2 -Wall -Wextra -std=c99 -Iinc -I. src/loragw_hal.c -o obj/loragw_hal.o
In file included from inc/loragw_reg.h:29:0,
                 from src/loragw_hal.c:26:
inc/config.h:3:28: warning: missing terminating " character
" #define LIBLORAGW_VERSION "5.0.1
                            ^
inc/config.h:4:1: warning: missing terminating " character
  #define DEBUG_AUX 0
 ^
inc/config.h:4:1: error: missing terminating " character
inc/config.h:3:28: error: missing terminating " character
" #define LIBLORAGW_VERSION "5.0.1
                            ^
src/loragw_hal.c:94:47: note: in expansion of macro ‘LIBLORAGW_VERSION’
 const char lgw_version_string[] = "Version: " LIBLORAGW_VERSION ";";
                                               ^~~~~~~~~~~~~~~~~
src/loragw_hal.c:94:65: error: expected ‘,’ or ‘;’ before string constant
 const char lgw_version_string[] = "Version: " LIBLORAGW_VERSION ";";
                                                                 ^~~
Makefile:67: recipe for target 'obj/loragw_hal.o' failed
make[1]: *** [obj/loragw_hal.o] Error 1
make[1]: Leaving directory '/home/pi/¬/Lora/lora_gateway/libloragw'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mcoracin** [comment]
Same answer as other issue.
