### ISSUE TITLE
SX1301 compile issue again

### ISSUE THREAD

**Issue by allionWilliam** [Lora-net/lora_gateway#72]
hi everyone

It`s me again.
I have error message after I use "make" command to compile the Packet_forwarder file.
I am really not familiar with coding, could anyone help me ?
I got the source from https://github.com/Lora-net/packet_forwarder

[packet_forwarder.docx](https://github.com/Lora-net/lora_gateway/files/1287487/packet_forwarder.docx)

**Comment by mcoracin** [comment]
It could be a a "end of line "issue in the VERSION file. It happens sometimes if you get the files through Microsoft Windows OS.
Either run a dos2unix command on the files or directly clone or unzip the software on the linux machine on which you compile, without having Windows in the middle.
