### ISSUE TITLE
RHF0M301

### ISSUE THREAD

**Issue by chelliwell** [Lora-net/lora_gateway#73]
Sorry, not a code issue, but this seemed a good place to ask: does anyone have experience of Risinghf's RHF0M301 concentrator board?
Is it 'compatible' with this project and, more importantly is it actually an available product and at what sort of price?
Thanks.

**Comment by JiapengLi** [comment]
Yes, it is compatible. For price, you may send email to salesww@risinghf.com.

**Comment by chelliwell** [comment]
I've tried that - unfortunately the email bounced:
"SMTP error from remote server for RCPT TO command, host: mxbiz1.qq.com (184.105.206.88) reason: 550 Ip frequency limited."
:(

**Comment by mcoracin** [comment]
Can't do anything about it here, closing the issue.
