### ISSUE TITLE
Reference design for SX1301 / SX1308

### ISSUE THREAD

**Issue by saboohajaz** [Lora-net/lora_gateway#75]
Hi,

I am developing a lora gateway based SX1301 and 1308.
While researching online, i found out that the reference designs are available only under NDA.
I am not sure how to proceed with that NDA.
Can someone please guide me?

**Comment by mcoracin** [comment]
Hi,
You con contact Semtech support through the LoRa community:
https://semtech.force.com/lora/LC_CommunityLogin_New

**Comment by saboohajaz** [comment]
I tried to register on the LC Community site.
But it is not accepting my email address.

I actually emailed 
LoRa_Community_Support@semtech.com

about the issue. Still waiting for reply

**Comment by mcoracin** [comment]
Can't do more about this here, closing the issue.
