### ISSUE TITLE
concentrator crash when  returned a packet with SF=0 (CRC error on LoRa header)    

### ISSUE THREAD

**Issue by vikasrohal** [Lora-net/lora_gateway#78]
Hi 
Concontrator crashed with an error "loating point exception" .
This bug fixed in lora_gateway version v1.2.1 but it still alive in version v5.0.1
please find attached screen  shot 

![screenshot from 2017-09-22 10-10-44](https://user-images.githubusercontent.com/23522407/30729995-1c976a92-9f53-11e7-8f39-e194254b54b4.png)

**Comment by mcoracin** [comment]
Hello,

Could you please give the payload (corrupted) that you received?
Because I've tried on the latest version by forcing sf to 0, and I got the following error, which is expected:
ERROR: [up] lora packet with unknown datarate

But to crash.

**Comment by mcoracin** [comment]
no answer, closing the issue.
