### ISSUE TITLE
Fatal error: can't create obj/util_spectral_scan.o: No such file or directory

### ISSUE THREAD

**Issue by vredzhepov** [Lora-net/lora_gateway#8]
The latest version of the lora_gateway build failed. The reason of this error is there's no obj directory in the util_spectral_scan directory.

make[1]: Entering directory `/tmp/lora_gateway-master/util_spectral_scan'
gcc -c -O2 -Wall -Wextra -std=c99 -I inc -D DEBUG_SPI=0 -D DEBUG_REG=0 src/util_spectral_scan.c -o obj/util_spectral_scan.o
Assembler messages:
Fatal error: can't create obj/util_spectral_scan.o: No such file or directory
make[1]: *** [obj/util_spectral_scan.o] Error 1
make[1]: Leaving directory `/tmp/lora_gateway-master/util_spectral_scan'
make: *** [all] Error 2

**Comment by JiapengLi** [comment]
Workaround:

     mkdir util_spectral_scan/obj

**Comment by mcoracin** [comment]
this will be fixed with next release, thanks for reporting.
