### ISSUE TITLE
 Question on SX1301

### ISSUE THREAD

**Issue by moonhyunkoo6356** [Lora-net/lora_gateway#84]
Hello.

I purchased LoRa IOT Starter Kits(SX1301 and Raspbbery Pi) last month and have a question about this.
 
We want to execute test example ‘test_loragw_gps’ and ‘gps_pkt_fwd’ in lora-net package. But I think GSP is not enabled because of something wrong in local_conf.json and global_conf.json files. The problem screen is below.

['test_lora_gps']
![image](https://user-images.githubusercontent.com/31286050/31860361-b591fff6-b753-11e7-92ac-7866e3f6f71f.png)

['gps_pkt_fwd']
![image](https://user-images.githubusercontent.com/31286050/31860370-c10dadb2-b753-11e7-9967-525e56e7375b.png)

WARNING: [gps] could not get UTC time from GPS

is our main issue and we really want to configure out this. 
for doing this, Should I change configure in my local_conf.json file? 
or another issue about hardware related with GSP?
My local_conf.json file is below
![image](https://user-images.githubusercontent.com/31286050/31860374-c7f60ba6-b753-11e7-9e6d-869a88150995.png)

Please help us about this. We really need your help.

Thank you.

**Comment by mcoracin** [comment]
What do you get if you type the following command?
> cat /dev/ttyAMA0

**Comment by mcoracin** [comment]
no answer, closing the issue.
