### ISSUE TITLE
Retry after missing ACK

### ISSUE THREAD

**Issue by siscia** [Lora-net/lora_gateway#85]
Hi : -)

after a push packet, if the packet is not ACKed from the server, is the packet re-send?

All I see is here: https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/src/lora_pkt_fwd.c#L1849

But I don't see any effort in re-trying to send an not ACKed packet.
(It could be just me not seeing something obvious...)

This behaviour (fire and forget) is the expected one?

**Comment by larkolab** [comment]
Yes, this behaviour is the expected one.

**Comment by siscia** [comment]
Great thank you!
