### ISSUE TITLE
NOT A VALID IF_CHAIN NUMBER

### ISSUE THREAD

**Issue by ghost** [Lora-net/lora_gateway#88]
Hello,

I am trying to get the software to run on a [Phytec Regor (site in german, sorry)](http://www.phytec.de/produkt/single-board-computer/phyboard-regor/). 
I am using the [iC880A - LoRaWAN® Concentrator](https://wireless-solutions.de/products/radiomodules/ic880a.html).

I setup everything correctly in terms of wiring. I double checked everything. Every helper program (from the library) is running without errors. 

The init process of the gateway is successful.
The problem with the lora_gateway is, I get the following error when receiving a message:
```sh
lgw_receive:1155: FIFO content: 1 10 0 7 ff
lgw_receive:1170: WARNING: 105 NOT A VALID IF_CHAIN NUMBER, ABORTING
```
The 5th byte read from the concentrator is always 0xFF. Has someone experienced such a behavior?

As I understand it the 5th byte is the size of the payload received by the gateway. But the packets I send have a payload of only 26 bytes.

As a sidenote I got everything running on the Raspberry Pi 2 without the error.

**Comment by EoinBullock** [comment]
did you find a solution for this issue?
