### ISSUE TITLE
LoRa Gateway for .NET

### ISSUE THREAD

**Issue by grahamehorner** [Lora-net/lora_gateway#9]
I'm researching and thinking about creating a .NET CoreCLR implementation of the LoRa gateway; does/has anyone any knowledge of any projects implementing a LoRA gateway using .NET CLR/CoreCLR.

The aim is to create a gateway that can run on Windows, Linux and OSX using the platform created by the CoreCLR/ASPNET teams.

**Comment by mcoracin** [comment]
On Semtech side, there is no plan to implement this.

As no other answers has been given, I close this issue.
