### ISSUE TITLE
read register mismatch on sx1301

### ISSUE THREAD

**Issue by ly1243667342** [Lora-net/lora_gateway#92]
###MISMATCH### reg number 4 read: 45 (2d) default: 0 (0)       LGW_RX_DATA_BUF_DATA
###MISMATCH### reg number 10 read: 155 (9b) default: 0 (0)   LGW_MCU_PROM_DATA
###MISMATCH### reg number 78 read: 31 (1f) default: 0 (0)      LGW_GPIO_PIN_REG_IN
###MISMATCH### reg number 285 read: 31 (1f) default: 0 (0)    LGW_DBG_ARB_MCU_RAM_DATA
###MISMATCH### reg number 286 read: 7 (7) default: 0 (0)       LGW_DBG_AGC_MCU_RAM_DATA
###MISMATCH### reg number 298 read: 7 (7) default: 0 (0)       LGW_DBG_DEC_FILT_GAIN

what is the problem?

**Comment by mcoracin** [comment]
no problem, those registers have undefined initial value after reset. You can ignore that.
