### ISSUE TITLE
Failed to load fw 1

### ISSUE THREAD

**Issue by zhoubx123** [Lora-net/lora_gateway#96]
HI , who can help me ?
ERROR: Failed to load fw 1
ERROR: Version of calibration firmware not expected, actual:49 expected:2
ERROR: [main] failed to start the concentrator

**Comment by Theoi-Meteoroi** [comment]
The first line is pretty clear. Firmware failed to load.
The second line complains about calibration firmware levels. You have the wrong firmware set for install.
The third line becomes obvious. Party over. Not today.

**Comment by 3nd0y** [comment]
@Theoi-Meteoroi which firmware did you mean? Is the concentrator has a firmware inside? I have similar issue but with error: actual:0 expected:2

**Comment by Dieter-D** [comment]
@zhoubx123 
Did you execute the reset script (https://github.com/Lora-net/lora_gateway/blob/master/reset_lgw.sh)  before starting the software?

**Comment by zhoubx123** [comment]
Thank you for  reply.
 My problem has been solved. when I shorten the SPI line and connect more ground lines.
