### ISSUE TITLE
SX1301 Reg Test

### ISSUE THREAD

**Issue by rego21** [Lora-net/lora_gateway#97]
Hello all,

Im trying to connect the SX1301 to on STM32L073 Nucleo. I ran the reg test and obtained the following results (image) :
![sem titulo](https://user-images.githubusercontent.com/25685147/35269836-245899bc-0025-11e8-9b89-12efdb256380.png)
Should i worry about this or anyone knows how to solve the problem? Because only have problems on two of them...

Thank you all!

**Comment by FlorianMarcon** [comment]
Hi @rego21 !

Have you find a solution ?

**Comment by rego21** [comment]
> 
> 
> Hi @rego21 !
> 
> Have you find a solution ?

Hi @FlorianMarcon 

Sorry for late response, i tried using STM32L073 but its not possible due to the lack of memory. You can try with a larger (memory) STM, it should work with any problems. ARM embedded has everything you need! 

Best regards!

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
