### ISSUE TITLE
SX1301 FirmWare Error

### ISSUE THREAD

**Issue by rego21** [Lora-net/lora_gateway#99]
Im trying the util_pkt_logger teste, but im haveing the following error:

**ERROR : Version of AGC firmware not expected, actual 2 expected: 4**.

I already ran the reg test and spi stress without any problems... 

Thank you!

**Comment by mcoracin** [comment]
How long did you run the spi stress test app, with which parameters? Because it is a typical issue for an SPI problem.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
